# Merge, Merge on Index

- Concatenation takes two DataFrames and produces one consisiting of the two on top of each other
- Merge works like JOIN in SQL by using a shared key
- Combine

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [7]:
sales1 = DataFrame({"Region": ["South", "North", "East", "West"], "Total Sales 1":[10000,20000,30000,40000]})
sales2 = DataFrame({"Region": ["South", "North", "North East"], "Total Sales 2":[12000,14000,16000]})

In [10]:
pd.merge(sales1,sales2) # Acts like an INNER JOIN by default - finds matching columns automatically

Region  Total Sales 1  Total Sales 2
0  South          10000          12000
1  North          20000          14000

In [11]:
pd.merge(sales1,sales2, on="Region") # Key columns may also be specified

Region  Total Sales 1  Total Sales 2
0  South          10000          12000
1  North          20000          14000

In [12]:
pd.merge(sales1,sales2, on="Region", how="outer") # Specifying a value for "how" allows you to change the nature of the join

Region  Total Sales 1  Total Sales 2
0       South        10000.0        12000.0
1       North        20000.0        14000.0
2        East        30000.0            NaN
3        West        40000.0            NaN
4  North East            NaN        16000.0

In [13]:
pd.merge(sales1,sales2,on="Region",how="left")

Region  Total Sales 1  Total Sales 2
0  South          10000        12000.0
1  North          20000        14000.0
2   East          30000            NaN
3   West          40000            NaN

In [17]:
sales5=DataFrame({"Region":["South","North","East","West"],"Total Sales 5":[25991,77342,88463,71946]})
sales6=DataFrame({"Total Sales 6":[88253,1288492,77261,39948], "Area":["South", "North East", "West", "South East"]})

In [18]:
pd.merge(sales5,sales6,left_on="Region",right_on="Area") # Note that the "Area" column is included as well 

Region  Total Sales 5  Total Sales 6   Area
0  South          25991          88253  South
1   West          71946          77261   West

## Merging on Index

In [14]:
sales3=DataFrame({"Region":["South","North","East","West"],"Total Sales 3":[25991,77342,88463,71946]})
sales4=DataFrame({"Total Sales 4":[88253,1288492,77261,39948]}, index = ["South", "North East", "West", "South East"])

In [16]:
pd.merge(sales3,sales4,left_on="Region",right_index=True) # Note that the syntax involving the index is slightly different

Region  Total Sales 3  Total Sales 4
0  South          25991          88253
3   West          71946          77261

## Concatenation

In [19]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.concatenate([arr1,arr1],axis=1) # "axis" specifies the direction of concatenation

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

### Concatenation in Series

In [27]:
ser1=Series([0,1,2],index=["T","U","V"])
ser2=Series([3,4],index=["W","X"])

In [30]:
pd.concat([ser1,ser2]) 

T    0
U    1
V    2
W    3
X    4
dtype: int64

In [34]:
pd.concat([ser1,ser2],axis=1,sort=True) 

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
W  NaN  3.0
X  NaN  4.0

In [36]:
pd.concat([ser1,ser2],keys=["cat1","cat2"]) # Adding keys allows you to see the original series after they've been joined

cat1  T    0
      U    1
      V    2
cat2  W    3
      X    4
dtype: int64

In [37]:
dframe1 = DataFrame(np.random.randn(4,3),columns=["x","y","z"])
dframe2 = DataFrame(np.random.randn(3,3),columns=["q","y","x"])

In [38]:
dframe1

x         y         z
0  0.833889  0.608392  0.029314
1 -0.985672  0.047505  1.505530
2 -0.548152 -0.277017 -1.893477
3  1.842213  1.140946  1.899818

In [39]:
dframe2

q         y         x
0  0.211080  0.067103  0.603468
1 -0.283940 -0.152237  0.977688
2 -0.255648  0.102544 -1.082144

In [51]:
pd.concat([dframe1,dframe2],sort=True) # note that the index, by default, will retain it's original values from each series

q         x         y         z
0       NaN  0.833889  0.608392  0.029314
1       NaN -0.985672  0.047505  1.505530
2       NaN -0.548152 -0.277017 -1.893477
3       NaN  1.842213  1.140946  1.899818
0  0.211080  0.603468  0.067103       NaN
1 -0.283940  0.977688 -0.152237       NaN
2 -0.255648 -1.082144  0.102544       NaN

In [52]:
pd.concat([dframe1,dframe2],sort=True,ignore_index=True) #ignore_index renumbers the index accordingly

q         x         y         z
0       NaN  0.833889  0.608392  0.029314
1       NaN -0.985672  0.047505  1.505530
2       NaN -0.548152 -0.277017 -1.893477
3       NaN  1.842213  1.140946  1.899818
4  0.211080  0.603468  0.067103       NaN
5 -0.283940  0.977688 -0.152237       NaN
6 -0.255648 -1.082144  0.102544       NaN